### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by schtritoff** [mvendert/LabelPrint#1]
Hi,

Trying to evaluate the software for label creation and distribution but I'm having hard time with demo scenario. Can you provide one working XML example for printjob, paper and label? I made XML's according to schema but I can't get pass [this](https://github.com/mvendert/LabelPrint/blob/21b91fb4afd78a2021d1d972348e3ebb7753d022/LabelDesigner/FormLabelDesignerEx.cs#L342) exception.

BR

**Comment by mvendert** [comment]
Setting it up correctly is not so simple.  This is done via a setup program that is not opensource but…

 

For evaluating I have a cmd file this this content. My files are on a drive D is a folder d:\data\sourcesafe2. References to this folder is in different config files and xml files.

 

start D:\data\SourceSafe2\AcaLabelX\ACALabelXTestClient\bin\x86\Debug\ACALabelXTestClient.exe            

start D:\data\SourceSafe2\AcaLabelX\ACALabelXTestServer\bin\x86\Debug\ACALabelXTestServer.exe

start D:\data\SourceSafe2\AcaLabelX\LabelControler\bin\x86\Debug\LabelControler.exe

start D:\data\SourceSafe2\AcaLabelX\LabelDesigner\bin\x86\Debug\LabelDesigner.exe

 

For example the designer LabelDesigner.exe.config contains:

 

<?xml version="1.0"?>

<configuration>

  <appSettings>

    <add key="ConfigXML" value="D:\data\SourceSafe2\AcaLabelX\ACALabelXServer\ACALabelXServer.config.xml" />

    <add key="logfile" value="D:\aca\ACALabelPrint\Logs\LabelDesignerLogging.txt" />

    <add key="append" value="false" />

    <add key="ClientSettingsProvider.ServiceUri" value="" />

  </appSettings>

  <startup>

    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />

  </startup>

  <system.web>

    <membership defaultProvider="ClientAuthenticationMembershipProvider">

      <providers>

        <add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" />

      </providers>

    </membership>

    <roleManager defaultProvider="ClientRoleProvider" enabled="true">

      <providers>

        <add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" cacheTimeout="86400" />

      </providers>

    </roleManager>

  </system.web>

</configuration>

 

The logfile folder should exist…

The configXML should exist and contain these entries (this file is present in the project.)

*remark: the labels are created on the server. The designer is meant to run on the server where you design the label, and label content and the resulting label defintions are distributed to the client. In this xml file, you put the name of the directory structure you created. Sample structure is mentioned in the files.

 

 

 

<?xml version="1.0"?>

<configuration>

  <system.runtime.remoting>

    <customErrors mode="off"/>

    <application name="ACALabelXServer">

      <channels>

        <channel address="127.0.0.1" ref="http" port="18080">

          <serverProviders>

            <formatter ref="soap" typeFilterLevel="Full"/>

            <formatter ref="binary" typeFilterLevel="Full"/>

            

            <provider type ="ACA.LabelX.TestServer.ClientIPInjectorSinkProvider, ACALabelXServer"/>

          </serverProviders> 

        </channel> 

      </channels>

      <service>

        <wellknown mode="Singleton" type="ACA.LabelX.RemoteObject, ACALabelXRemoteObject" objectUri="ACALabelXRemoteObject" />

      </service>

    </application>

    <debug loadtypes="true" />

  </system.runtime.remoting>

  <general-settings>

    <allowed_versions begin="0.01" end="0.05" />



    <folders>

      <PrintJobsRootFolder>D:\ACA\ACALabelPrint\Server PrintJobs</PrintJobsRootFolder>

      <LabelDefinitionsRootFolder>D:\ACA\ACALabelPrint\Server LabelDefinitions</LabelDefinitionsRootFolder>

      <PaperDefinitionsRootFolder>D:\ACA\ACALabelPrint\Server PaperDefinitions</PaperDefinitionsRootFolder>

      <SettingsRootFolder>D:\ACA\ACALabelPrint\Server Settings</SettingsRootFolder>

      <PicturesRootFolder>D:\ACA\ACALabelPrint\Server Pictures</PicturesRootFolder>

      <UpdateRootFolder>D:\ACA\ACALabelPrint\Server Updates</UpdateRootFolder>

    </folders>    

  </general-settings>

</configuration>


There folders should all exist.

The testclient also has such a file and all these directories should exist also.

 

Then… you can only design if a printjob with data exists… this you need to have first. You select a printjob and then design a label for it.

But now I remember… this was a sourceforge project at first. The ‘sample’ folders did not survive the move to github.

 

May this  <https://sourceforge.net/projects/labelprint/files/labelprint/2.0/> https://sourceforge.net/projects/labelprint/files/labelprint/2.0/ and then  <https://sourceforge.net/projects/labelprint/files/labelprint/2.0/ACALabelPrint_samplefolders.rar/download> ACALabelPrint_samplefolders.rar

Might be helpful… There are the needed files for the folder structure and some sample files. The app.config files for each exe needs to be correct first though.

 

But my main remark is. Check all XML files contained in the project and check the app.config files for directory names. That is often the main issue here.

 

Van Endert Marc
Kloosterstraat 3 bus 1
3530 Houthalen

GPS (WGS84)  : N 051-01.906' - E 005-22.180'

GPS (BEL1950): N 051-01.988' - E 005-22.135'

 

GSM : +32 476 360603
WWW :  <http://www.vanendert.com/> www.vanendert.com  of  <http://www.endert.be/> www.endert.be
Mail: marc@vanendert.com <mailto:marc@vanendert.com>  of marc@endert.be <mailto:marc@endert.be>
